# This file contains configuration settings for stylua, a code formatter for Lua
# It ensures consistent code formatting across the project

column_width = 120 # Sets the maximum line length before wrapping
line_endings = "Unix" # Uses Unix-style line endings (LF) for cross-platform compatibility
indent_type = "Spaces" # Uses spaces instead of tabs for indentation
indent_width = 2 # Sets the number of spaces for each indentation level
quote_style = "AutoPreferDouble" # Automatically chooses between single and double quotes, preferring double quotes
call_parentheses = "None" # Removes parentheses in function calls when possible
